use_frameworks!

install! 'cocoapods', :generate_multiple_pod_projects => true, :incremental_installation => true, :disable_input_output_paths => true, :warn_for_unused_master_specs_repo => false

platform :ios, '10.0'

def tiaoshi
  # 模块对外服务
  pod 'Services', :path => './PodsCompoent', :project_name => 'Services'
  # 登录服务
  pod 'LoginModule', :path => './PodsCompoent', :project_name => 'Module'
  # 用户服务
  pod 'UserModule', :path => './PodsCompoent', :project_name => 'Module'
  # 商品服务
  pod 'GoodsModule', :path => './PodsCompoent', :project_name => 'Module'
  # 购物车服务
  pod 'ShopCartModule', :path => './PodsCompoent', :project_name => 'Module'
end

target 'MJRouter_Example' do
  
  tiaoshi
  
  pod 'MJRouter', :path => '../'
  
  
  target 'MJRouter_Tests' do
    inherit! :search_paths

    
  end
end
